version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
  file-converter:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - BODY_SIZE_LIMIT=0
      - ORIGIN=http://localhost:3000
    depends_on:
      - mongo